[tool.poetry]
name = "mqtt_influxdb_gateway"
version = "0.1.0"
description = "An MQTT gateway sending data to InfluxDB"
authors = ["Radek Lát <radek.lat@gmail.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
